/**
 * @module routes/controllers/root
 * @fileoverview Root route's controller. Exports functions to be used by each
 *    route handler.
 */


/**
 * @function sendHomepage
 * @description Send the base homepage rendered by `Handlebars.js`. Compilation
 *    of HBS templates is handled by the HBS engine.
 * @param {Object} req The request object generated by `Express`.
 * @param {Object} res The response object generated by `Express`.
 * @param {Function} next The function to call when this method is done executing
 *    and does not return or render anything (no `res` methods called).
 */
const sendHomepage = (req, res, next) => {
  res.render('homepage', { title: 'Sample Web Page' });
}


module.exports = {
  sendHomepage,
}
