/**
 * @module routes/controllers/user
 * @fileoverview User route's controller. Handle all business logic relative to
 *    a particular user or a set of users.
 */


/**
 * @function login
 * @description Log a user in based on the received form data from the client.
 * @param {Object} req The request object generated by `Express`.
 * @param {Object} res The response object generated by `Express`.
 * @param {Function} next The function to call when this method is done executing
 *    and does not return or render anything (no `res` methods called).
 */
const login = (req, res, next) => {
  // Capture user-submitted form from client.

  // Example:
  // const { username, password } = req.body;

  // Do something with the username / password. Verify the password hash?
  // Check if the user exists? etc.

  // Redirect to another route or maybe render a different page?
  res.render('userpage');
}


module.exports = {
  login,
}
